# The following lines were added by compinstall
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' format '-> Completing %d'
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}' '' '' ''
zstyle ':completion:*' original true
zstyle :compinstall filename '<HOME-DIR>/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory
bindkey -v
# End of lines configured by zsh-newuser-install

# Fuzzy finder stuff
__fzfcmd() {
  __fzf_use_tmux__ &&
    echo "fzf-tmux -d${FZF_TMUX_HEIGHT:-40%}" || echo "fzf"
}

__fzf_use_tmux__() {
  [ -n "$TMUX_PANE" ] && [ "${FZF_TMUX:-0}" != 0 ] && [ ${LINES:-40} -gt 15 ]
}

# CTRL-R - Paste the selected command from history into the command line
fzf-history-widget() {
  local selected num
  setopt localoptions noglobsubst noposixbuiltins pipefail 2> /dev/null
  selected=( $(fc -rl 1 |
    FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS --query=${(qqq)LBUFFER} +m" $(__fzfcmd)) )
  local ret=$?
  if [ -n "$selected" ]; then
    num=$selected[1]
    if [ -n "$num" ]; then
      zle vi-fetch-history -n $num
    fi
  fi
  zle redisplay
  typeset -f zle-line-init >/dev/null && zle zle-line-init
  return $ret
}
zle     -N   fzf-history-widget
bindkey '^R' fzf-history-widget

# About duplicated commands
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_BEEP

# Aliases
alias ls='ls --color=auto'
alias lls='ls --color=auto'
alias ll='ls -l --color=auto'
alias la='ls -a --color=auto'
alias lla='ls -al --color=auto'
alias cd..='cd ..'
alias l='ls --color=auto'
alias s='ls --color=auto'
alias lls='ls --color=auto'
alias ip='ip --color'
alias ipb='ip --color --brief'
alias stop='sudo systemctl stop'
alias start='sudo systemctl start'
alias status='sudo systemctl status'
alias disable='sudo systemctl disable'
alias enable='sudo systemctl enable'
alias restart='sudo systemctl restart'
alias pacman="sudo pacman"
alias aura='aura -x'
alias quit='exit'
alias gocfg='cd <CODE-PROJECTS>/configs'

# Prompt configuration
autoload -U colors && colors
function makeprompt() {
  printf "%s\n%s" \
    "%B%(?.%{$fg[green]%}[✔]%{$reset_color%}%B.%{$fg[red]%}[✖]%{$reset_color%}%B) %n@%m %{$fg[blue]%}(%~)%{$reset_color%}%B" \
    "(%!) %{$fg[blue]%}%(!.#.$)%{$reset_color%}%b "
}
export PS1="$(makeprompt)"

# Prompt vim
function zle-line-init zle-keymap-select {
  VIM_PROMPT="%{$fg_bold[green]%} [% NORMAL]%{$reset_color%}"
  RPS1="%{$(echotc UP 1)%}%B%D{%c}%b${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}%{$(echotc DO 1)%}"
  zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select

# Key bindinng (VI)
export KEYTIMEOUT=1 # Remove delay for entering/exiting modes
bindkey '^w' backward-kill-word

# When using !!,!$,etc. the command will wait, not execute right away
setopt no_hist_verify
